export const categories = [
  {
    id: 1,
    name: "Burgers",
    description: "Hamburgers, cheeseburgers, and specialty burgers",
    image: require("../assets/categories/hamburger.png"),
  },
  {
    id: 2,
    name: "Pizza",
    description: "Various types of pizza and Italian fast food",
    image: require("../assets/categories/pizza.png"),
  },
  {
    id: 3,
    name: "Pasta",
    description: "Spaghetti, noodles, and Italian pasta dishes",
    image: require("../assets/categories/spaghetti.png"),
  },
  {
    id: 4,
    name: "Desserts",
    description: "Cupcakes, sweets, and dessert items",
    image: require("../assets/categories/cupcake.png"),
  },
  {
    id: 5,
    name: "Takeout",
    description: "Various takeout and delivery options",
    image: require("../assets/categories/takeout-box.png"),
  },
  {
    id: 7,
    name: "Beverages",
    description: "Tropical drinks, smoothies, and refreshing beverages",
    image: require("../assets/categories/tropical-drink.png"),
  },
  {
    id: 8,
    name: "Seafood",
    description: "Fish, tropical seafood, and marine delicacies",
    image: require("../assets/categories/tropical-fish.png"),
  },
];
export const restaurantsWithCategories = [
  {
    id: "1",
    name: "Pakistani",
    description: "Spicy curries, biryanis, BBQ and traditional street food.",
    restaurants: [
      {
        id: "1",
        name: "Ahsan Food",
        image: require("../assets/restaurants/ahsan-food.webp"),
        rating: 4.5,
        reviews: 120,
        location: "Karachi, Pakistan",
        deliveryTime: "25-30 min",
        category: "Pakistani",
      },
      {
        id: "2",
        name: "Desi Food",
        image: require("../assets/restaurants/desi-foods.jpg"),
        rating: 4.8,
        reviews: 210,
        location: "Lahore, Pakistan",
        deliveryTime: "35-40 min",
        category: "Pakistani",
      },
      {
        id: "1",
        name: "Ahsan Food",
        image: require("../assets/restaurants/ahsan-food.webp"),
        rating: 4.5,
        reviews: 120,
        location: "Karachi, Pakistan",
        deliveryTime: "25-30 min",
        category: "Pakistani",
      },
      {
        id: "2",
        name: "Desi Food",
        image: require("../assets/restaurants/desi-foods.jpg"),
        rating: 4.8,
        reviews: 210,
        location: "Lahore, Pakistan",
        deliveryTime: "35-40 min",
        category: "Pakistani",
      },
    ],
  },
  {
    id: "2",
    name: "Fast Food",
    description: "Burgers, fries, fried chicken and quick bites.",
    restaurants: [
      {
        id: "3",
        name: "KFC",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.2,
        reviews: 500,
        location: "New York, USA",
        deliveryTime: "20-25 min",
        category: "Fast Food",
      },
      {
        id: "4",
        name: "Burger Lab",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 450,
        location: "Dubai, UAE",
        deliveryTime: "20-25 min",
        category: "Fast Food",
      },
      {
        id: "3",
        name: "KFC",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.2,
        reviews: 500,
        location: "New York, USA",
        deliveryTime: "20-25 min",
        category: "Fast Food",
      },
      {
        id: "4",
        name: "Burger Lab",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 450,
        location: "Dubai, UAE",
        deliveryTime: "20-25 min",
        category: "Fast Food",
      },
    ],
  },
  {
    id: "3",
    name: "Pizza",
    description: "Cheesy pizzas with endless topping choices.",
    restaurants: [
      {
        id: "5",
        name: "Papa Johns",
        image: require("../assets/restaurants/papa-johns.jpg"),
        rating: 4.6,
        reviews: 340,
        location: "Los Angeles, USA",
        deliveryTime: "30-35 min",
        category: "Pizza",
      },
      {
        id: "6",
        name: "La Piazza",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.6,
        reviews: 280,
        location: "Rome, Italy",
        deliveryTime: "25-35 min",
        category: "Pizza",
      },
    ],
  },
  {
    id: "4",
    name: "Middle Eastern",
    description: "Shawarma, falafel, hummus, kebabs and rice dishes.",
    restaurants: [
      {
        id: "7",
        name: "Al-Baik",
        image: require("../assets/restaurants/al-baik.jpeg"),
        rating: 4.7,
        reviews: 430,
        location: "Jeddah, Saudi Arabia",
        deliveryTime: "20-30 min",
        category: "Middle Eastern",
      },
      {
        id: "8",
        name: "Falafel King",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 260,
        location: "Cairo, Egypt",
        deliveryTime: "20-30 min",
        category: "Middle Eastern",
      },
    ],
  },
  {
    id: "5",
    name: "Japanese",
    description: "Fresh sushi, ramen, tempura and Japanese delicacies.",
    restaurants: [
      {
        id: "9",
        name: "Sushi Master",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.9,
        reviews: 300,
        location: "Tokyo, Japan",
        deliveryTime: "40-45 min",
        category: "Japanese",
      },
    ],
  },
  {
    id: "6",
    name: "Mexican",
    description: "Tacos, burritos, nachos and spicy Mexican street food.",
    restaurants: [
      {
        id: "10",
        name: "El Taco Loco",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.4,
        reviews: 410,
        location: "Mexico City, Mexico",
        deliveryTime: "30-40 min",
        category: "Mexican",
      },
    ],
  },
  {
    id: "7",
    name: "Chinese",
    description: "Noodles, dim sum, stir-fries and flavorful sauces.",
    restaurants: [
      {
        id: "11",
        name: "Dragon Wok",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 370,
        location: "Beijing, China",
        deliveryTime: "25-30 min",
        category: "Chinese",
      },
    ],
  },
  {
    id: "8",
    name: "Seafood",
    description: "Fresh fish, prawns, crab and grilled seafood platters.",
    restaurants: [
      {
        id: "12",
        name: "Ocean Catch",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.8,
        reviews: 310,
        location: "Sydney, Australia",
        deliveryTime: "35-45 min",
        category: "Seafood",
      },
    ],
  },
  {
    id: "9",
    name: "Bakery",
    description: "Fresh bread, cakes, pastries and sweet desserts.",
    restaurants: [
      {
        id: "13",
        name: "Bakery Bliss",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 150,
        location: "London, UK",
        deliveryTime: "15-20 min",
        category: "Bakery",
      },
    ],
  },
];
