export const categories = [
  {
    id: 1,
    name: "Burgers",
    description: "Hamburgers, cheeseburgers, and specialty burgers",
    image: require("../assets/categories/hamburger.png"),
  },
  {
    id: 2,
    name: "Pizza",
    description: "Various types of pizza and Italian fast food",
    image: require("../assets/categories/pizza.png"),
  },
  {
    id: 3,
    name: "Pasta",
    description: "Spaghetti, noodles, and Italian pasta dishes",
    image: require("../assets/categories/spaghetti.png"),
  },
  {
    id: 4,
    name: "Desserts",
    description: "Cupcakes, sweets, and dessert items",
    image: require("../assets/categories/cupcake.png"),
  },
  {
    id: 5,
    name: "Takeout",
    description: "Various takeout and delivery options",
    image: require("../assets/categories/takeout-box.png"),
  },
  {
    id: 7,
    name: "Beverages",
    description: "Tropical drinks, smoothies, and refreshing beverages",
    image: require("../assets/categories/tropical-drink.png"),
  },
  {
    id: 8,
    name: "Seafood",
    description: "Fish, tropical seafood, and marine delicacies",
    image: require("../assets/categories/tropical-fish.png"),
  },
];
export const restaurantsWithCategories = [
  {
    id: "1",
    name: "Pakistani",
    description: "Spicy curries, biryanis, BBQ and traditional street food.",
    restaurants: [
      {
        id: "1",
        name: "Ahsan Food",
        image: require("../assets/restaurants/ahsan-food.webp"),
        rating: 4.5,
        reviews: 120,
        location: "Karachi, Pakistan",
        deliveryTime: "25-30 min",
        category: "Pakistani",
        description: "Authentic Pakistani karahi and BBQ dishes",
      },
      {
        id: "2",
        name: "Desi Food",
        image: require("../assets/restaurants/desi-foods.jpg"),
        rating: 4.8,
        reviews: 210,
        location: "Lahore, Pakistan",
        deliveryTime: "35-40 min",
        category: "Pakistani",
        description: "Traditional Lahori nihari and breakfast",
      },
      {
        id: "3",
        name: "Spice Village",
        image: require("../assets/restaurants/ahsan-food.webp"),
        rating: 4.3,
        reviews: 95,
        location: "Islamabad, Pakistan",
        deliveryTime: "30-35 min",
        category: "Pakistani",
        description: "Modern Pakistani cuisine",
      },
      {
        id: "4",
        name: "BBQ Tonight",
        image: require("../assets/restaurants/desi-foods.jpg"),
        rating: 4.6,
        reviews: 180,
        location: "Rawalpindi, Pakistan",
        deliveryTime: "40-45 min",
        category: "Pakistani",
        description: "Premium grilled meats and tandoori",
      },
    ],
  },
  {
    id: "2",
    name: "Fast Food",
    description: "Burgers, fries, fried chicken and quick bites.",
    restaurants: [
      {
        id: "5",
        name: "KFC",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.2,
        reviews: 500,
        location: "New York, USA",
        deliveryTime: "20-25 min",
        category: "Fast Food",
        description: "World famous fried chicken",
      },
      {
        id: "6",
        name: "Burger Lab",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 450,
        location: "Dubai, UAE",
        deliveryTime: "20-25 min",
        category: "Fast Food",
        description: "Gourmet burgers and fries",
      },
      {
        id: "7",
        name: "McDonald's",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.1,
        reviews: 600,
        location: "Chicago, USA",
        deliveryTime: "15-20 min",
        category: "Fast Food",
        description: "Classic burgers and happy meals",
      },
      {
        id: "8",
        name: "Subway",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.0,
        reviews: 380,
        location: "London, UK",
        deliveryTime: "25-30 min",
        category: "Fast Food",
        description: "Fresh sandwiches and salads",
      },
    ],
  },
  {
    id: "3",
    name: "Pizza",
    description: "Cheesy pizzas with endless topping choices.",
    restaurants: [
      {
        id: "9",
        name: "Papa Johns",
        image: require("../assets/restaurants/papa-johns.jpg"),
        rating: 4.6,
        reviews: 340,
        location: "Los Angeles, USA",
        deliveryTime: "30-35 min",
        category: "Pizza",
        description: "Fresh dough and premium toppings",
      },
      {
        id: "10",
        name: "La Piazza",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.6,
        reviews: 280,
        location: "Rome, Italy",
        deliveryTime: "25-35 min",
        category: "Pizza",
        description: "Authentic Italian wood-fired pizza",
      },
      {
        id: "11",
        name: "Domino's",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 420,
        location: "Texas, USA",
        deliveryTime: "20-25 min",
        category: "Pizza",
        description: "Fast delivery hot pizza",
      },
    ],
  },
  {
    id: "4",
    name: "Middle Eastern",
    description: "Shawarma, falafel, hummus, kebabs and rice dishes.",
    restaurants: [
      {
        id: "12",
        name: "Al-Baik",
        image: require("../assets/restaurants/al-baik.jpeg"),
        rating: 4.7,
        reviews: 430,
        location: "Jeddah, Saudi Arabia",
        deliveryTime: "20-30 min",
        category: "Middle Eastern",
        description: "Famous Arabic fried chicken",
      },
      {
        id: "13",
        name: "Falafel King",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 260,
        location: "Cairo, Egypt",
        deliveryTime: "20-30 min",
        category: "Middle Eastern",
        description: "Best falafel and shawarma",
      },
      {
        id: "14",
        name: "Lebanese House",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.4,
        reviews: 190,
        location: "Beirut, Lebanon",
        deliveryTime: "30-40 min",
        category: "Middle Eastern",
        description: "Traditional mezze and grills",
      },
    ],
  },
  {
    id: "5",
    name: "Japanese",
    description: "Fresh sushi, ramen, tempura and Japanese delicacies.",
    restaurants: [
      {
        id: "15",
        name: "Sushi Master",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.9,
        reviews: 300,
        location: "Tokyo, Japan",
        deliveryTime: "40-45 min",
        category: "Japanese",
        description: "Fresh sushi and sashimi",
      },
      {
        id: "16",
        name: "Ramen House",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.7,
        reviews: 220,
        location: "Osaka, Japan",
        deliveryTime: "35-40 min",
        category: "Japanese",
        description: "Authentic ramen noodles",
      },
    ],
  },
  {
    id: "6",
    name: "Mexican",
    description: "Tacos, burritos, nachos and spicy Mexican street food.",
    restaurants: [
      {
        id: "17",
        name: "El Taco Loco",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.4,
        reviews: 410,
        location: "Mexico City, Mexico",
        deliveryTime: "30-40 min",
        category: "Mexican",
        description: "Spicy tacos and burritos",
      },
      {
        id: "18",
        name: "Burrito Express",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 180,
        location: "Cancun, Mexico",
        deliveryTime: "25-35 min",
        category: "Mexican",
        description: "Fresh Mexican bowls",
      },
    ],
  },
  {
    id: "7",
    name: "Chinese",
    description: "Noodles, dim sum, stir-fries and flavorful sauces.",
    restaurants: [
      {
        id: "19",
        name: "Dragon Wok",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 370,
        location: "Beijing, China",
        deliveryTime: "25-30 min",
        category: "Chinese",
        description: "Sizzling stir-fries and noodles",
      },
      {
        id: "20",
        name: "Panda Express",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.2,
        reviews: 290,
        location: "Shanghai, China",
        deliveryTime: "20-25 min",
        category: "Chinese",
        description: "Orange chicken and fried rice",
      },
    ],
  },
  {
    id: "8",
    name: "Seafood",
    description: "Fresh fish, prawns, crab and grilled seafood platters.",
    restaurants: [
      {
        id: "21",
        name: "Ocean Catch",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.8,
        reviews: 310,
        location: "Sydney, Australia",
        deliveryTime: "35-45 min",
        category: "Seafood",
        description: "Fresh grilled fish and prawns",
      },
      {
        id: "22",
        name: "Fish Market",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.5,
        reviews: 240,
        location: "San Francisco, USA",
        deliveryTime: "30-40 min",
        category: "Seafood",
        description: "Daily fresh seafood specials",
      },
    ],
  },
  {
    id: "9",
    name: "Bakery",
    description: "Fresh bread, cakes, pastries and sweet desserts.",
    restaurants: [
      {
        id: "23",
        name: "Bakery Bliss",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.3,
        reviews: 150,
        location: "London, UK",
        deliveryTime: "15-20 min",
        category: "Bakery",
        description: "Fresh bread and pastries",
      },
      {
        id: "24",
        name: "Sweet Tooth",
        image: require("../assets/restaurants/kfc.webp"),
        rating: 4.6,
        reviews: 210,
        location: "Paris, France",
        deliveryTime: "20-25 min",
        category: "Bakery",
        description: "Delicious cakes and desserts",
      },
    ],
  },
];
export const dishesData = [
  {
    id: "1",
    name: "Chicken Biryani",
    description:
      "Fragrant basmati rice cooked with tender chicken pieces and aromatic spices",
    price: 12.99,
    image: require("../assets/dishes/image1.jpeg"),
    category: "Main Course",
    rating: 4.8,
    calories: 650,
    preparationTime: "30-40 min",
  },
  {
    id: "2",
    name: "Beef Burger",
    description:
      "Juicy beef patty with fresh vegetables and special sauce in a sesame bun",
    price: 8.99,
    image: require("../assets/dishes/image2.jpeg"),
    category: "Fast Food",
    rating: 4.5,
    calories: 720,
    preparationTime: "15-20 min",
  },
  {
    id: "3",
    name: "Margherita Pizza",
    description:
      "Classic pizza with tomato sauce, fresh mozzarella, and basil leaves",
    price: 10.5,
    image: require("../assets/dishes/image3.jpeg"),
    category: "Italian",
    rating: 4.6,
    calories: 850,
    preparationTime: "20-25 min",
  },
  {
    id: "4",
    name: "Vegetable Salad",
    description:
      "Fresh mix of greens, tomatoes, cucumbers, and olives with dressing",
    price: 7.25,
    image: require("../assets/dishes/image4.jpeg"),
    category: "Healthy",
    rating: 4.3,
    calories: 220,
    preparationTime: "10 min",
  },
  {
    id: "5",
    name: "Chocolate Cake",
    description:
      "Rich chocolate cake with creamy frosting and chocolate shavings",
    price: 5.99,
    image: require("../assets/dishes/image5.jpeg"),
    category: "Dessert",
    rating: 4.9,
    calories: 480,
    preparationTime: "5 min",
  },
  {
    id: "6",
    name: "Grilled Salmon",
    description:
      "Fresh salmon fillet grilled to perfection with lemon butter sauce",
    price: 16.75,
    image: require("../assets/dishes/image6.jpeg"),
    category: "Seafood",
    rating: 4.7,
    calories: 420,
    preparationTime: "25-30 min",
  },
  {
    id: "7",
    name: "Chicken Tikka",
    description: "Marinated chicken pieces grilled in traditional tandoor",
    price: 11.25,
    image: require("../assets/dishes/image7.jpeg"),
    category: "Appetizer",
    rating: 4.6,
    calories: 320,
    preparationTime: "20-25 min",
  },
  {
    id: "8",
    name: "Vegetable Stir Fry",
    description: "Assorted vegetables stir-fried in savory sauce with tofu",
    price: 9.5,
    image: require("../assets/dishes/image8.jpeg"),
    category: "Vegetarian",
    rating: 4.4,
    calories: 280,
    preparationTime: "15-20 min",
  },
  {
    id: "9",
    name: "Beef Steak",
    description:
      "Premium cut of beef grilled to your preference with side vegetables",
    price: 18.99,
    image: require("../assets/dishes/image9.jpeg"),
    category: "Main Course",
    rating: 4.8,
    calories: 580,
    preparationTime: "25-35 min",
  },
  {
    id: "10",
    name: "Fruit Platter",
    description: "Seasonal selection of fresh fruits beautifully arranged",
    price: 6.75,
    image: require("../assets/dishes/image10.jpeg"),
    category: "Healthy",
    rating: 4.2,
    calories: 150,
    preparationTime: "5-10 min",
  },
  {
    id: "11",
    name: "Spaghetti Carbonara",
    description:
      "Classic Italian pasta with creamy sauce, pancetta, and parmesan",
    price: 13.25,
    image: require("../assets/dishes/image11.jpeg"),
    category: "Italian",
    rating: 4.7,
    calories: 670,
    preparationTime: "20-25 min",
  },
  {
    id: "12",
    name: "Mango Smoothie",
    description: "Refreshing blend of ripe mangoes, yogurt, and honey",
    price: 4.99,
    image: require("../assets/dishes/image12.jpeg"),
    category: "Beverage",
    rating: 4.5,
    calories: 210,
    preparationTime: "5 min",
  },
  {
    id: "13",
    name: "Cheesecake",
    description: "Creamy New York-style cheesecake with berry compote",
    price: 6.5,
    image: require("../assets/dishes/image13.jpeg"),
    category: "Dessert",
    rating: 4.9,
    calories: 520,
    preparationTime: "5 min",
  },
  {
    id: "14",
    name: "Chicken Wings",
    description: "Crispy chicken wings with your choice of sauce",
    price: 8.25,
    image: require("../assets/dishes/image14.jpeg"),
    category: "Appetizer",
    rating: 4.6,
    calories: 450,
    preparationTime: "20-25 min",
  },
  {
    id: "15",
    name: "Vegetable Soup",
    description: "Hearty soup made with fresh vegetables and herbs",
    price: 5.75,
    image: require("../assets/dishes/image15.jpeg"),
    category: "Starter",
    rating: 4.3,
    calories: 180,
    preparationTime: "15 min",
  },
];
